"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
ENVIRONMENT = os.environ.get("ENVIRONMENT", "development")
if ENVIRONMENT.lower() == "development":
    env_file = BASE_DIR / ".env"
    if env_file.exists():
        environ.Env.read_env(str(env_file))

# SILENCED_SYSTEM_CHECKS = True
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8n*qbt-wp(k$j7x@65rl@$=bk+t1+dtdv0lj+&5!vywd%g@sb*"

DATA_UPLOAD_MAX_MEMORY_SIZE = 62428800  # 50MB (adjust as needed)
FILE_UPLOAD_MAX_MEMORY_SIZE = 62428800  # 50MB (adjust as needed)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = [
    f"http://{os.environ.get('crf', 'localhost')}:8000",
    "http://localhost:8088",
    "http://192.168.0.51:8088",
    "http://192.168.0.50:8088",
    "http://41.111.138.26:8088",
    "http://41.111.138.26:8090",
]
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Application definition
CORS_ORIGIN_ALLOW_ALL = True


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "graphene_django",
    "django_extensions",
    "django_filters",
    "rest_framework",
    "qr_code",
    "graphql_jwt.refresh_token.apps.RefreshTokenConfig",
    "corsheaders",
    "libs",
    # apps;
    "immo",
    "inventory",
]

GRAPHQL_JWT = {
    "JWT_VERIFY_EXPIRATION": False,
    "JWT_EXPIRATION_DELTA": timedelta(days=300),
    "JWT_REFRESH_EXPIRATION_DELTA": timedelta(days=300),
    "JWT_LONG_RUNNING_REFRESH_TOKEN": True,
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "libs.utils.middleware.JSONWebTokenMiddleware",
    "libs.utils.get_user.ThreadLocalMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
CORS_ALLOW_HEADERS = [
    "content-type",
    "content-type",
    "authorization",
    "x-csrftoken",
]
CORS_ALLOW_ALL_ORIGINS = True

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'raillogistic.middleware.JSONWebTokenMiddleware',
#     'raillogistic.get_user.ThreadLocalMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

ROOT_URLCONF = "root.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "template")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "root.wsgi.application"

# DATABASE_ROUTERS = ("rh.routers.WorkerRouter",)


# Database

DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default="postgresql://mkhaled:KhaledRM250@localhost:5432/inventory_system",
    )
}

GRAPHENE_DJANGO_FILTER = {
    "FILTER_KEY": "filter",
    "AND_KEY": "and",
    "OR_KEY": "or",
    "NOT_KEY": "not",
}

APPEND_SLASH = False

# Graphene
GRAPHENE = {
    # 'RELAY_CONNECTION_ENFORCE_FIRST_OR_LAST': True,
    "RELAY_CONNECTION_MAX_LIMIT": 100,
    "SCHEMA": "root.schema.schema",
    "SCHEMA_INDENT": 4,
    "MIDDLEWARE": [
        "graphql_jwt.middleware.JSONWebTokenMiddleware",
        "graphene_django.debug.DjangoDebugMiddleware",
        # 'graphene_django_extras.ExtraGraphQLDirectiveMiddleware'
    ],
}

AUTHENTICATION_BACKENDS = [
    "graphql_jwt.backends.JSONWebTokenBackend",
    "django.contrib.auth.backends.ModelBackend",
]


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Static and Media

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = "/staticfiles/"

STATIC_ROOT = "staticfiles"
# Extra places for collectstatic to find static files.

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

# typically, os.path.join(os.path.dirname(__file__), 'media')

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"


# Time and Languages

TIME_ZONE = "Africa/Algiers"
FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400

USE_I18N = True

USE_L10N = True
LANGUAGE_CODE = "fr"
USE_TZ = True
USE_I18N = True
USE_L10N = True
USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = ","
THOUSAND_SEPARATOR = "."
NUMBER_GROUPING = 3


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "mail.rail-logistic.dz"
EMAIL_HOST_USER = "erp@rail-logistic.dz"
EMAIL_HOST_PASSWORD = "MILKhaledRM250"  # past the key or password app here
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# IMAP settings


EMAIL_CONFIGS = {
    "facturation": {
        "EMAIL_HOST": "mail.rail-logistic.dz",
        "IMAP_SERVER": "mail.rail-logistic.dz",
        "SMTP_SERVER": "mail.rail-logistic.dz",
        "EMAIL_HOST_USER": "erp@rail-logistic.dz",
        "EMAIL_USER": "erp@rail-logistic.dz",
        "IMAP_USER": "erp@rail-logistic.dz",
        "SMTP_USER": "erp@rail-logistic.dz",
        "EMAIL_PORT": 587,
        "SMTP_PORT": 587,
        "EMAIL_PASSWORD": "railmail-2025",
        "IMAP_PASSWORD": "railmail-2025",
        "SMTP_PASSWORD": "railmail-2025",
        "EMAIL_HOST_PASSWORD": "railmail-2025",
        "EMAIL_USE_TLS": True,
    },
}

FRONTEND = "http://localhost:3000"


# advanced_filters = {
#     "sum":{
#         "Entreprise__transaction__count"
#     }
# }


SEQUENCES = {
    "2025": {
        "FactureAvoir": 1,
        "Devis": 1,
        "FicheFacturation": 1,
    }
}

IGNORE_GQL_AUTH = [
    "tms",
    "relations/emptycontratitem",
    "/admin",
    "auth",
    "graphql",
    "not_found",
    "reporting",
    "/favicon.ico",
    # "/facturation/",
    "/qr/",
    "data/import",
    "/facturation/test/",
    "/facturation/creances",
    "/billing/proforma/",
    "maintenance/reporting/sinistre",
    "commands/docs",
    "docs",
    "/parc/vehicules",
    "/models/generate",
    "billing/attachements",
    "gen",
    "/dossiers/attachement/",
    "/graphiql",
    "login",
    "/auth",
    "/export",
    "/media",
    "/maintenance/reporting",
    # "/facturation/facturebordereau/",
    "backup",
]


MODEL_DATE = {"FactureItem": "related__date"}
