# Generated by Django 4.2.13 on 2025-12-20 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("immo", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampagneInventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de creation de l'enregistrement.",
                        verbose_name="Cree le",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de derniere modification.",
                        verbose_name="Modifie le",
                    ),
                ),
                (
                    "code_campagne",
                    models.CharField(
                        help_text="Identifiant fonctionnel unique de la campagne.",
                        max_length=50,
                        unique=True,
                        verbose_name="Code de campagne",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Libelle utilise pour identifier la campagne.",
                        max_length=150,
                        verbose_name="Nom de campagne",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True,
                        help_text="Date effective de lancement.",
                        null=True,
                        verbose_name="Date de debut",
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Date de cloture ou fin prevue.",
                        null=True,
                        verbose_name="Date de fin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne d'inventaire",
                "verbose_name_plural": "Campagnes d'inventaire",
                "ordering": ("-cree_le", "nom"),
            },
        ),
        migrations.CreateModel(
            name="GroupeComptage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de creation de l'enregistrement.",
                        verbose_name="Cree le",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de derniere modification.",
                        verbose_name="Modifie le",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Identifiant court pour reconnaitre l'equipe de comptage.",
                        max_length=150,
                        verbose_name="Nom du groupe",
                    ),
                ),
                (
                    "appareil_identifiant",
                    models.CharField(
                        help_text="Identifiant unique de l'appareil utilise pour scanner.",
                        max_length=120,
                        unique=True,
                        verbose_name="Identifiant de l'appareil",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("COMPTAGE", "Comptage")],
                        default="COMPTAGE",
                        help_text="Role unique de l'equipe (comptage).",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Notes ou informations internes sur le groupe.",
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "campagne",
                    models.ForeignKey(
                        help_text="Campagne a laquelle le groupe est rattache.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groupes",
                        to="inventory.campagneinventaire",
                        verbose_name="Campagne",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        help_text="Utilisateur rattache au groupe de comptage.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groupes_comptage",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Groupe de comptage",
                "verbose_name_plural": "Groupes de comptage",
                "ordering": ("nom",),
            },
        ),
        migrations.CreateModel(
            name="EnregistrementInventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de creation de l'enregistrement.",
                        verbose_name="Cree le",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de derniere modification.",
                        verbose_name="Modifie le",
                    ),
                ),
                (
                    "code_article",
                    models.CharField(
                        help_text="Code unique scanne sur l'article (peut etre repete).",
                        max_length=300,
                        verbose_name="Code article",
                    ),
                ),
                (
                    "capture_le",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date et heure de capture du scan.",
                        verbose_name="Capture le",
                    ),
                ),
                (
                    "source_scan",
                    models.CharField(
                        blank=True,
                        help_text="Origine du scan (camera, RFID, manuel...).",
                        max_length=100,
                        verbose_name="Source du scan",
                    ),
                ),
                (
                    "donnees_capture",
                    models.JSONField(
                        blank=True,
                        help_text="Donnees supplementaires liees a l'enregistrement.",
                        null=True,
                        verbose_name="Donnees de capture",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True,
                        help_text="Notes complementaires associees a l'enregistrement.",
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Article reference si le code correspond au referentiel.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enregistrements_inventaire",
                        to="immo.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "campagne",
                    models.ForeignKey(
                        help_text="Campagne rattachee a cet enregistrement.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enregistrements",
                        to="inventory.campagneinventaire",
                        verbose_name="Campagne",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direction ou departement selectionne pour le comptage.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enregistrements_inventaire",
                        to="immo.department",
                        verbose_name="Departement",
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        help_text="Groupe ayant effectue le scan.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enregistrements",
                        to="inventory.groupecomptage",
                        verbose_name="Groupe de comptage",
                    ),
                ),
                (
                    "lieu",
                    models.ForeignKey(
                        help_text="Lieu selectionne pour le comptage (direction, location, ...).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enregistrements_inventaire",
                        to="immo.location",
                        verbose_name="Lieu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enregistrement d'inventaire",
                "verbose_name_plural": "Enregistrements d'inventaire",
                "ordering": ("-capture_le",),
            },
        ),
    ]
