# Generated by Django 4.2.13 on 2025-12-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_groupecomptage_pin_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="enregistrementinventaire",
            name="etat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BIEN", "Bien"),
                    ("MOYENNE", "Moyenne"),
                    ("HORS_SERVICE", "Hors service"),
                ],
                help_text="Etat du materiel lors de l'enregistrement.",
                max_length=20,
                null=True,
                verbose_name="Etat du materiel",
            ),
        ),
    ]
