# Generated by Django 4.2.13 on 2025-12-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_enregistrementinventaire_etat"),
        ("inventory", "0003_groupecomptage_lieux_autorises"),
    ]

    operations = []
