# Generated by Django 4.2.13 on 2025-12-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_merge_20251221_1632"),
    ]

    operations = [
        migrations.AddField(
            model_name="enregistrementinventaire",
            name="observation",
            field=models.TextField(blank=True, null=True, verbose_name="Observation"),
        ),
        migrations.AddField(
            model_name="enregistrementinventaire",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Numéro de série"
            ),
        ),
    ]
