# Generated by Django 4.2.13 on 2025-12-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_enregistrementinventaire_observation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enregistrementinventaire",
            name="observation",
            field=models.TextField(
                blank=True,
                help_text="Observation complementaire associee a l'enregistrement.",
                null=True,
                verbose_name="Observation",
            ),
        ),
        migrations.AlterField(
            model_name="enregistrementinventaire",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Numero de serie associe a l'article scanne.",
                max_length=100,
                null=True,
                verbose_name="Numero de serie",
            ),
        ),
    ]
