# Generated by Django 4.2.13 on 2025-12-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_enregistrementinventaire_observation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enregistrementinventaire",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image associee a l'enregistrement.",
                null=True,
                upload_to="inventaire/images",
                verbose_name="Image",
            ),
        ),
    ]
