# Generated by Django 4.2.13 on 2025-12-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_enregistrementinventaire_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="enregistrementinventaire",
            name="custom_desc",
            field=models.TextField(
                blank=True,
                help_text="Description personnalisée associee a l'enregistrement.",
                null=True,
                verbose_name="Description personnalisée",
            ),
        ),
    ]
