# Generated by Django 4.2.13 on 2025-12-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_enregistrementinventaire_custom_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="enregistrementinventaire",
            name="image2",
            field=models.ImageField(
                blank=True,
                help_text="Image associee a l'enregistrement.",
                null=True,
                upload_to="inventaire/images",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="enregistrementinventaire",
            name="image3",
            field=models.ImageField(
                blank=True,
                help_text="Image associee a l'enregistrement.",
                null=True,
                upload_to="inventaire/images",
                verbose_name="Image",
            ),
        ),
    ]
