# Generated by Django 4.2.13 on 2025-12-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_enregistrementinventaire_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enregistrementinventaire",
            name="latitude",
            field=models.CharField(
                blank=True,
                help_text="Latitude associee a l'enregistrement.",
                max_length=30,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="enregistrementinventaire",
            name="longitude",
            field=models.CharField(
                blank=True,
                help_text="Longitude associee a l'enregistrement.",
                max_length=30,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
