# Generated by Django 4.2.13 on 2026-01-27 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("immo", "__first__"),
        ("inventory", "0010_enregistrementinventaire_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de creation de l'enregistrement.",
                        verbose_name="Cree le",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de derniere modification.",
                        verbose_name="Modifie le",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        db_column="description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        help_text="Code-barres unique pour identifier l'emplacement.",
                        max_length=100,
                        unique=True,
                        verbose_name="Code-barres",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emplacement",
                "verbose_name_plural": "Emplacements",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PositionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de creation de l'enregistrement.",
                        verbose_name="Cree le",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de derniere modification.",
                        verbose_name="Modifie le",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du type"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        db_column="description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type d'emplacement",
                "verbose_name_plural": "Types d'emplacement",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ScannedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de creation de l'enregistrement.",
                        verbose_name="Cree le",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de derniere modification.",
                        verbose_name="Modifie le",
                    ),
                ),
                (
                    "code_article",
                    models.CharField(
                        help_text="Code unique scanne sur l'article.",
                        max_length=300,
                        verbose_name="Code article",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BIEN", "Bien"),
                            ("MOYENNE", "Moyenne"),
                            ("HORS_SERVICE", "Hors service"),
                        ],
                        help_text="Etat du materiel lors de l'enregistrement.",
                        max_length=20,
                        null=True,
                        verbose_name="Etat du materiel",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Numero de serie associe a l'article scanne.",
                        max_length=100,
                        null=True,
                        verbose_name="Numero de serie",
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True,
                        help_text="Observation complementaire associee a l'enregistrement.",
                        null=True,
                        verbose_name="Observation",
                    ),
                ),
                (
                    "source_scan",
                    models.CharField(
                        blank=True,
                        help_text="Origine du scan (integrated scanner, RFID, manuel...).",
                        max_length=100,
                        verbose_name="Source du scan",
                    ),
                ),
                (
                    "capture_le",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date et heure de capture du scan.",
                        verbose_name="Capture le",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Article reference si le code correspond au referentiel.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scans_inventaire",
                        to="immo.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "campagne",
                    models.ForeignKey(
                        help_text="Campagne rattachee a cet enregistrement.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles_scannes",
                        to="inventory.campagneinventaire",
                        verbose_name="Campagne",
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        help_text="Groupe ayant effectue le scan.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles_scannes",
                        to="inventory.groupecomptage",
                        verbose_name="Groupe de comptage",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        help_text="Emplacement ou l'article a ete scanne.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles_scannes",
                        to="inventory.position",
                        verbose_name="Emplacement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article scanne",
                "verbose_name_plural": "Articles scannes",
                "ordering": ("-capture_le",),
            },
        ),
        migrations.AddField(
            model_name="position",
            name="location_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="inventory.positiontype",
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="inventory.position",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("parent", "name")},
        ),
    ]
