# Generated by Django 4.2.13 on 2026-01-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("immo", "__first__"),
        ("inventory", "0011_position_positiontype_scannedarticle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RapprochementInventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de creation de l'enregistrement.",
                        verbose_name="Cree le",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de derniere modification.",
                        verbose_name="Modifie le",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RapprochementInventaireDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de creation de l'enregistrement.",
                        verbose_name="Cree le",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de derniere modification.",
                        verbose_name="Modifie le",
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Confirmé?"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observation"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Article rattache a ce detail.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rapprochements_details",
                        to="immo.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "rapprochement",
                    models.ForeignKey(
                        help_text="Rapprochement rattache a ce detail.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="inventory.rapprochementinventaire",
                        verbose_name="Rapprochement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
