# Generated by Django 4.2.13 on 2026-01-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_rapprochementinventaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupecomptage",
            name="compare_to_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Groupe avec lequel comparer les scans.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groupes_comparaison",
                to="inventory.groupecomptage",
                verbose_name="Groupe de comparaison",
            ),
        ),
    ]
