# Generated by Django 4.2.13 on 2026-01-27 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("immo", "__first__"),
        ("inventory", "0013_groupecomptage_compare_to_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="enregistrementinventaire",
            name="is_extra",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Est extra?"
            ),
        ),
        migrations.AlterField(
            model_name="rapprochementinventairedetail",
            name="article",
            field=models.ForeignKey(
                blank=True,
                help_text="Article rattache a ce detail.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rapprochements_details",
                to="immo.article",
                verbose_name="Article",
            ),
        ),
    ]
