# Generated by Django 4.2.13 on 2026-01-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("immo", "__first__"),
        ("inventory", "0014_enregistrementinventaire_is_extra_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rapprochementinventairedetail",
            options={
                "verbose_name": "Détail du rapprochement",
                "verbose_name_plural": "Détails du rapprochement",
            },
        ),
        migrations.AddField(
            model_name="rapprochementinventaire",
            name="campagne",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rapprochement",
                to="inventory.campagneinventaire",
                verbose_name="Campagne",
            ),
        ),
        migrations.AddField(
            model_name="rapprochementinventairedetail",
            name="code_article",
            field=models.CharField(
                blank=True,
                help_text="Code article (utile pour les surplus non references).",
                max_length=300,
                verbose_name="Code article",
            ),
        ),
        migrations.AddField(
            model_name="rapprochementinventairedetail",
            name="statut",
            field=models.CharField(
                choices=[
                    ("MATCH", "Correspondance"),
                    ("MANQUANT", "Manquant (Ecart Négatif)"),
                    ("SURPLUS", "Surplus (Ecart Positif)"),
                ],
                default="MATCH",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="groupecomptage",
            name="role",
            field=models.CharField(
                choices=[
                    ("COMPTAGE", "Comptage"),
                    ("CONTROLE", "Contrôle / Supervision"),
                ],
                default="COMPTAGE",
                help_text="Role unique de l'equipe (comptage).",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="rapprochementinventairedetail",
            name="article",
            field=models.ForeignKey(
                blank=True,
                help_text="Article reference si le code correspond au referentiel.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rapprochements_details",
                to="immo.article",
                verbose_name="Article",
            ),
        ),
    ]
